import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { redirect } from 'next/navigation';

import introduce from '/public/introduce.png';
import bannerImg from '/public/banner_pic.png';

import male from '/public/male.png';
import female from '/public/female.png';
import product_users from '/public/product_users.png';

import { Button } from '@/components/ui/button';
import ExplainerSection from '@/components/ExplainerSection';
import PricingSection from '@/components/PricingSection';
import ProductCarousel from '@/components/ProductCarousel';
import { Rate } from 'antd';

export const dynamic = 'force-dynamic';

export default async function Index() {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect('/overview');
  }

  return (
    <div className='flex flex-col items-center pt-16 px-20'>
      <div className='flex flex-col lg:flex-row items-center gap-8 p-8 w-full bg-[#E0FAFA] px-20 rounded-lg space-y-8'>
        <div className='flex flex-col space-y-4 lg:w-2/5 w-full'>
          <h1 className='text-6xl font-bold'>
            <span className='text-transparent text-[#167ef9]'>
              Professional AI Headshots
            </span>{' '}
            in minutes.
          </h1>
          <p className='text-lg'>
            Elevate your online presence with HD headshots generated by our AI. Ideal for social
            profiles, resumes, and professional portfolios.
          </p>
          <div className='flex flex-col space-y-2'>
            <Link href='/login'>
              <Button className='lg:w-2/3 py-6 px-2 md:px-8 mt-4 shadow-md md:mt-6 text-xl flex w-full md:w-auto  md:inline-flex justify-center items-center rounded-full  font-semibold bg-[#167ef9] hover:bg-[#167ef9] focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all'>
                Create Headshots Now
              </Button>
            </Link>
            <p className='text-lg'>
            451,520 + happy customers
            </p>
            <div className='flex smallimages'>
              <img
                src={product_users.src}
                alt='AI headshot'
                className='rounded-lg object-cover h-[45px]'
              />
              <Rate disabled defaultValue={5} />
            </div>
          </div>
        </div>
        <div className='lg:w-3/5 w-full mt-8 lg:mt-0'>
          <img
            src={bannerImg.src}
            alt='AI headshot'
            className='rounded-lg object-cover w-full'
            style={{ float: 'right' }}
          />
        </div>
      </div>
      <hr />
      {/*AI Photos part*/}
      {/*start*/}
      <div
        className='w-full px-20 mt-16 p-8 bg-gray-100 rounded-lg space-y-8 lg:py-10'
        style={{ position: 'relative' }}
      >
        <div className='w-full relative h-[600px]'>
          <h1 className='text-5xl font-bold text-transparent bg-clip-text text-[#167ef9] pb-8'>
            We do AI photoshoots
          </h1>
          <h1 className='text-2xl font-semibold mt-0'>
            Real photos generated for our real customers. See our results and reviews for yourself.
          </h1>
          <div className='banner-scroll'>
            <div className='banner-row d-flex to-left'>
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-1.png'
                alt='pro headshot sample1'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-2.png'
                alt='pro headshot sample2'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-3.png'
                alt='pro headshot sample3'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-4.png'
                alt='pro headshot sample4'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-5.png'
                alt='pro headshot sample5'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-6.png'
                alt='pro headshot sample6'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-7.png'
                alt='pro headshot sample7'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-8.png'
                alt='pro headshot sample8'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-1.png'
                alt='pro headshot sample1'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-2.png'
                alt='pro headshot sample2'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-3.png'
                alt='pro headshot sample3'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-4.png'
                alt='pro headshot sample4'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-5.png'
                alt='pro headshot sample5'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-6.png'
                alt='pro headshot sample6'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-7.png'
                alt='pro headshot sample7'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/male-8.png'
                alt='pro headshot sample8'
                className='banner-pic'
              />
            </div>
            <div className='banner-row d-flex to-right mt-3'>
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-1.png'
                alt='pro headshot sample9'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-2.png'
                alt='pro headshot sample10'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-3.png'
                alt='pro headshot sample11'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-4.png'
                alt='pro headshot sample12'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-5.png'
                alt='pro headshot sample13'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-6.png'
                alt='pro headshot sample14'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-7.png'
                alt='pro headshot sample15'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-8.png'
                alt='pro headshot sample16'
                className='banner-pic'
              />
              <img
                src='https://images.media.io/images2023/ai-headshot-generator/female-1.png'
                alt='pro headshot sample9'
                className='banner-pic'
              />
            </div>
          </div>
        </div>
      </div>
      {/* end */}

      <ExplainerSection />
      <PricingSection />
    </div>
  );
}
